name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # Important for pushing changes
          fetch-depth: 0 # Needed for proper git history
      
      - uses: Platane/snk@v3
        with:
          github_user_name: FaithMutua-code
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
      
      - name: Push to branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animation [skip ci]"
          git push origin HEAD:${{ github.ref }}
